### ISSUE TITLE
Incompatible provider version

### ISSUE THREAD

**Issue by michaelrode** [kelvintaywl/terraform-provider-circleci#58]
# Summary 
Unable to use this provider due to Incompatible provider version. 

```
tf --version
Terraform v0.15.5
on darwin_amd64
```

```
terraform {
  required_providers {
    circleci = {
      source  = "kelvintaywl/circleci"
    }
  }
}

```
```
╷
│ Error: Incompatible provider version
│
│ No compatible versions of provider registry.terraform.io/kelvintaywl/circleci were found.
╵
```

**Comment by kelvintaywl** [comment]
Hi @michaelrode 

Given that Terraform v0.15.x is rather out of date, would you be able to upgrade to 1.x and see if the issue still persists?

ref: https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md

**Comment by kelvintaywl** [comment]
I’ll close this since there has been no follo-up.
Let me know if this is still an issue after upgrading to Terraform v1.x on your Mac Intel.
