### ISSUE TITLE
Update Provider Documentation

### ISSUE THREAD

**Issue by jtreutel** [kelvintaywl/terraform-provider-circleci#59]
### Info
Terraform version: `1.7.4`

### Current Behavior:

When inserting the provider into a Terraform plan as shown on [the docs page](https://registry.terraform.io/providers/kelvintaywl/circleci/latest/docs), Terraform throws the following error:

```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/circleci: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/circleci
│ 
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module. To see which modules are
│ currently depending on hashicorp/circleci, run the following command:
│     terraform providers
```

### Expected behavior:

Dropping the provider config in a Terraform plan would Just Work™. 

### Proposed solution:

Update `docs/index.html' to change the proposed provider config from this:

```
provider "circleci" {
  # info goes here
}
```

to this:

```
terraform {
  required_providers {
    circleci = {
      source  = "kelvintaywl/circleci"
    }
  }
}

provider "circleci" {
  # info goes here
}
```

**Comment by kelvintaywl** [comment]
hey @jtreutel 👋 😉 

thanks for the heads-up!
I had forgotten about that section, and assumed folks copy-pasted [directly from the registry UI ](https://registry.terraform.io/providers/kelvintaywl/circleci/latest/docs) as I do:

<img width="1363" alt="Screenshot 2024-02-28 at 13 15 10" src="https://github.com/kelvintaywl/terraform-provider-circleci/assets/2164346/b9ae04a3-bb47-4e7b-8bcb-17dc4b6edc6b">

making a doc PR @ #60

**Comment by kelvintaywl** [comment]
ayee, I would need to make a release (i.e., v0.12.1) to have the updated docs here be propagated on https://registry.terraform.io/providers/kelvintaywl/circleci/latest/docs 😆 

will do so soon 🌮

**Comment by jtreutel** [comment]
Ah, didn't know it could be found there!  TIL!  Thanks for the quick fix 💯
